name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 检出仓库

      - name: Set up Rust
        uses: actions/setup-rust@v2  # 设置 Rust 环境

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential  # 安装构建必要的依赖，如果需要的话
          cargo build --release  # 构建 release 版本

      - name: Package for Linux
        run: cargo build --release --target=x86_64-unknown-linux-gnu  # 构建 Linux 版本

      - name: Package for Windows
        run: cargo build --release --target=x86_64-pc-windows-msvc  # 构建 Windows 版本

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: krak2-dist
          path: |
            target/release/krak2  # 上传编译产物，注意替换为你的实际二进制文件路径

      - name: Upload artifacts to releases
        id: upload-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/krak2
        # 根据需要添加更多文件

      - name: Publish to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'target/release/*.zip'  # 根据需要调整文件类型和路径
          token: ${{ secrets.GITHUB_TOKEN }}
